import Head from 'next/head'
import { usePokemons } from 'queries/hooks/usePokemons'

export default function Home() {
  const { data } = usePokemons(10, 0)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto p-10'>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    </>
  )
}
